// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

/*
Package go_micro_service_user is a generated protocol buffer package.

It is generated from these files:
	proto/user/user.proto

It has these top-level messages:
	UserLoginRequest
	UserLoginResponse
	UserRegisterRequest
	UserRegisterResponse
	UserInfoRequest
	UserInfoResponse
*/
package go_micro_service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserLoginRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UserLoginRequest) Reset()                    { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()               {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserLoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	IsLoginSuccess string `protobuf:"bytes,1,opt,name=is_login_success,json=isLoginSuccess" json:"is_login_success,omitempty"`
}

func (m *UserLoginResponse) Reset()                    { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()               {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserLoginResponse) GetIsLoginSuccess() string {
	if m != nil {
		return m.IsLoginSuccess
	}
	return ""
}

type UserRegisterRequest struct {
	UserName  string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
}

func (m *UserRegisterRequest) Reset()                    { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()               {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserRegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type UserRegisterResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *UserRegisterResponse) Reset()                    { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()               {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserRegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserInfoRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *UserInfoRequest) Reset()                    { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()               {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserInfoRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserInfoResponse struct {
	UserId    int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
}

func (m *UserInfoResponse) Reset()                    { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()               {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserInfoResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfoResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLoginRequest)(nil), "go.micro.service.user.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "go.micro.service.user.UserLoginResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "go.micro.service.user.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "go.micro.service.user.UserRegisterResponse")
	proto.RegisterType((*UserInfoRequest)(nil), "go.micro.service.user.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "go.micro.service.user.UserInfoResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xb5, 0xfd, 0xd9, 0x3f, 0x23, 0x68, 0x5d, 0x2d, 0x96, 0x88, 0x20, 0x7b, 0xb0, 0x45,
	0x61, 0x15, 0x3d, 0x7b, 0x96, 0xa2, 0x78, 0x88, 0x78, 0x13, 0x6a, 0x4c, 0xa7, 0x61, 0xc1, 0x64,
	0xeb, 0x4e, 0xa2, 0x9f, 0xca, 0xef, 0x28, 0xbb, 0x9b, 0x95, 0x36, 0x48, 0x5a, 0xf0, 0x92, 0x30,
	0x33, 0xef, 0xcd, 0x9b, 0x99, 0xc7, 0xc2, 0x60, 0xa1, 0x55, 0xae, 0x2e, 0x0a, 0x42, 0x6d, 0x3f,
	0xc2, 0xc6, 0x6c, 0x90, 0x28, 0x91, 0xca, 0x58, 0x2b, 0x41, 0xa8, 0x3f, 0x64, 0x8c, 0xc2, 0x14,
	0xf9, 0x1d, 0xf4, 0x9f, 0x08, 0xf5, 0xbd, 0x4a, 0x64, 0x16, 0xe2, 0x7b, 0x81, 0x94, 0xb3, 0x23,
	0xe8, 0x99, 0xda, 0x34, 0x8b, 0x52, 0x1c, 0x36, 0x4e, 0x1a, 0xe3, 0x5e, 0xd8, 0x35, 0x89, 0x87,
	0x28, 0x45, 0x16, 0x40, 0x77, 0x11, 0x11, 0x7d, 0x2a, 0x3d, 0x1b, 0x36, 0x5d, 0xcd, 0xc7, 0xfc,
	0x06, 0xf6, 0x96, 0x9a, 0xd1, 0x42, 0x65, 0x84, 0x6c, 0x0c, 0x7d, 0x49, 0xd3, 0x37, 0x93, 0x9b,
	0x52, 0x11, 0xc7, 0x48, 0x54, 0x36, 0xdd, 0x91, 0x64, 0xa1, 0x8f, 0x2e, 0xcb, 0x53, 0xd8, 0x37,
	0xf4, 0x10, 0x13, 0x49, 0xb9, 0xf9, 0xff, 0x6d, 0x1c, 0x76, 0x0c, 0x30, 0x97, 0x9a, 0x72, 0xc7,
	0x6c, 0xd9, 0x6a, 0xcf, 0x66, 0x0c, 0x95, 0x5f, 0xc2, 0xc1, 0xaa, 0x5c, 0x39, 0xf0, 0x10, 0x3a,
	0x29, 0x12, 0x45, 0x89, 0x57, 0xf3, 0x21, 0x17, 0xb0, 0x6b, 0x18, 0x93, 0x6c, 0xae, 0x36, 0x19,
	0x8e, 0x27, 0xee, 0xb8, 0x0e, 0x5f, 0x76, 0x3f, 0x84, 0x8e, 0x25, 0xc8, 0x99, 0x85, 0xb7, 0xc2,
	0xb6, 0x09, 0x27, 0xb3, 0xd5, 0x4e, 0xcd, 0xca, 0x9a, 0xf5, 0xab, 0x5c, 0x7d, 0x35, 0xe1, 0xbf,
	0x51, 0x62, 0xcf, 0xb0, 0x65, 0x4f, 0xca, 0x46, 0xe2, 0x57, 0xbf, 0x45, 0xd5, 0xec, 0x60, 0xbc,
	0x1e, 0xe8, 0x26, 0xe7, 0xff, 0x18, 0x42, 0xd7, 0x5f, 0x8b, 0x9d, 0xd5, 0xf0, 0x2a, 0x0e, 0x06,
	0xe7, 0x1b, 0x61, 0x7f, 0x64, 0x5e, 0x60, 0xfb, 0x16, 0x73, 0x7f, 0x39, 0x76, 0x5a, 0xc3, 0x5e,
	0xb2, 0x22, 0x18, 0xad, 0xc5, 0x79, 0x85, 0xd7, 0xb6, 0x7d, 0x13, 0xd7, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x40, 0x48, 0x85, 0xdc, 0x2c, 0x03, 0x00, 0x00,
}
